# Generated by Django 4.2.3 on 2023-07-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, blank=True),
            preserve_default=False,
        ),
    ]
